services:
  db:
    image: mysql:8.0
    container_name: pokemon_container
    environment:
      MYSQL_DATABASE: mypokemonDB
      MYSQL_USER: enos
      MYSQL_PASSWORD: Enos!2486
      MYSQL_ROOT_PASSWORD: Enos!2486
    ports:
      - "3307:3306"
    volumes:
      - mysql_data3:/var/lib/mysql

volumes:
  mysql_data3: